version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo "Packaging artifacts..."
      - mv $CODEBUILD_SRC_DIR/target/reinforced.war ROOT.war
artifacts:
  files:
    - ROOT.war
