version: 0.1

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo "Packaging artifacts..."
      - mv $CODEBUILD_SRC_DIR/target/reinforced.war ROOT.war
artifacts:
  files:
    - ROOT.war
