version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo "Packaging artifacts..."
artifacts:
  files:
    - ROOT.war
